const actions = {
  ADD_NAME: 'EDIT_NAME',
  EDIT_NAME: 'EDIT_NAME',
  BEGIN_EDIT_NAME: 'BEGIN_EDIT_NAME',
  END_EDIT_NAME: 'END_EDIT_NAME',

  ADD_EMAIL: 'EDIT_EMAIL',
  EDIT_EMAIL: 'EDIT_EMAIL',
  BEGIN_EDIT_EMAIL: 'BEGIN_EDIT_MAIL',
  END_EDIT_EMAIL: 'END_EDIT_MAIL',

  ADD_EDUCATION: 'ADD_EDUCATION',
  REMOVE_EDUCATION: 'REMOVE_EDUCATION',
  EDIT_EDUCATION: 'EDIT_EDUCATION',
  BEGIN_EDIT_EDUCATION: 'BEGIN_EDIT_EDUCATION',
  END_EDIT_EDUCATION: 'END_EDIT_EDUCATION',

  ADD_EMPLOYMENT: 'ADD_EMPLOYMENT',
  REMOVE_EMPLOYMENT: 'REMOVE_EMPLOYMENT',
  EDIT_EMPLOYMENT: 'EDIT_EMPLOYMENT',
  BEGIN_EDIT_EMPLOYMENT: 'BEGIN_EDIT_EMPLOYMENT',
  END_EDIT_EMPLOYMENT: 'END_EDIT_EMPLOYMENT',

  ADD_SKILL: 'ADD_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  EDIT_SKILL: 'EDIT_SKILL',
  BEGIN_EDIT_SKILL: 'BEGIN_EDIT_SKILL',
  END_EDIT_SKILL: 'END_EDIT_SKILL',

  ADD_INTEREST: 'ADD_INTEREST',
  REMOVE_INTEREST: 'REMOVE_INTEREST',
  EDIT_INTEREST: 'EDIT_INTEREST',
  BEGIN_EDIT_INTEREST: 'BEGIN_EDIT_INTEREST',
  END_EDIT_INTEREST: 'END_EDIT_INTEREST',

  ADD_PROFILE: 'ADD_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  BEGIN_EDIT_PROFILE: 'BEGIN_EDIT_PROFILE',
  END_EDIT_PROFILE: 'END_EDIT_PROFILE',

  EXPORT_JSON: 'EXPORT_JSON',
  EXPORT_HTML: 'EXPORT_HTML'
};

export default actions;