const actions = {
  EDIT_NAME: 'EDIT_NAME',
  EDIT_EMAIL: 'EDIT_EMAIL',

  ADD_EDUCATION: 'ADD_EDUCATION',
  REMOVE_EDUCATION: 'REMOVE_EDUCATION',
  EDIT_EDUCATION: 'EDIT_EDUCATION',

  ADD_EMPLOYMENT: 'ADD_EMPLOYMENT',
  REMOVE_EMPLOYMENT: 'REMOVE_EMPLOYMENT',
  EDIT_EMPLOYMENT: 'EDIT_EMPLOYMENT',

  ADD_SKILL: 'ADD_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  EDIT_SKILL: 'EDIT_SKILL',

  ADD_INTEREST: 'ADD_INTEREST',
  REMOVE_INTEREST: 'REMOVE_INTEREST',
  EDIT_INTEREST: 'EDIT_INTEREST',

  ADD_PROFILE: 'ADD_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',

  EXPORT_JSON: 'EXPORT_JSON',
  EXPORT_HTML: 'EXPORT_HTML'
};

export default actions;